### ISSUE TITLE
Question about baseline on ImageNet

### ISSUE THREAD

**Issue by ElvishElvis** [sachit-menon/classify_by_description_release#1]
Hello! Thanks for the great work!
I was running this codebase off-the-shelf on imageNet, and here's the accuracy I get, which doesn't quite match the baseline mentioned in the paper( 58.46) . Also as noted from the original CLIP paper, ViT-B/32 have zero shot accuracy of 63.2 (https://github.com/openai/CLIP/issues/24). Could you provide some further instruction on how to obtain the baseline( 58.46) mentioned in the paper? Thanks! 

Total Description-based Top-1 Accuracy:  62.65624761581421
Total Description-based Top-5 Accuracy:  86.56250238418579
Total CLIP-Standard Top-1 Accuracy:  60.78125238418579
Total CLIP-Standard Top-5 Accuracy:  84.0624988079071

**Comment by sachit-menon** [comment]
Hi, thanks for your interest and for pointing this out. I discovered a couple of differences that snuck in when I prepared the code for release that weren't in the development code that have now been corrected and pushed. The main differences are 
- There was a break statement in that prevented full evaluation from running.
- OpenAI's codebase for some reason doesn't include three of the ImageNet categories (eft, maillot, and projectile). (Probably because dropping them somehow improves their performance.) I added them back. 
- The OpenAI result is also reported with full ensembling of 80 prompts I believe. When we compare with both using all prompts, we still see a performance improvement but less -- probably you could get as big an increase with prompt tuning specific to descriptors.
- The suffix '.' is added to the end.

Now you should get a result more like the paper.
