### ISSUE TITLE
Does the result require manual data cleaning

### ISSUE THREAD

**Issue by RuoyuChen10** [sachit-menon/classify_by_description_release#3]
Hello, I would like to ask whether the JSON files you listed have been artificially cleaned. Because I try GPT3 may generate some strange answers.

```
What are useful features for distinguishing a tiger in a photo?

There are several features that can be used to distinguish a tiger in a photo:

1. Stripes: Tigers have unique stripe patterns on their fur, which can help to identify them. The stripes are usually black or dark brown on a light orange background.

2. Head shape: The shape of a tiger's head, including the size and placement of the ears, can be used to distinguish one individual from another.

3. Eye color: Tigers have yellow or amber-colored eyes, which can help to identify them in a photo.

4. Nose shape: The shape and size of a tiger's nose can be used to differentiate one individual from another.

5. Body size and shape: Tigers can vary in size and shape, so noting these characteristics can help to distinguish one tiger from another.

6. Behavior: A tiger's behavior in a photo, such as posture or movement, can also provide clues to its identity.

By looking at a combination of these features, it may be possible to distinguish one tiger from another in a photo.
```

**Comment by sachit-menon** [comment]
Hi, the outputs in the json were directly obtained from GPT3. Did you use the prompt provided in the generate_descriptors file? It looks like the prompt you used may not include the dash at the end to indicate a list, or the two examples (lemur and television).
________________________________
From: Ruoyu Chen ***@***.***>
Sent: Tuesday, March 7, 2023 10:48:52 AM
To: sachit-menon/classify_by_description_release ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sachit-menon/classify_by_description_release] Does the result require manual data cleaning (Issue #3)


Hello, I would like to ask whether the JSON files you listed have been artificially cleaned. Because I try GPT3 may generate some strange answers.

What are useful features for distinguishing a tiger in a photo?

There are several features that can be used to distinguish a tiger in a photo:

1. Stripes: Tigers have unique stripe patterns on their fur, which can help to identify them. The stripes are usually black or dark brown on a light orange background.

2. Head shape: The shape of a tiger's head, including the size and placement of the ears, can be used to distinguish one individual from another.

3. Eye color: Tigers have yellow or amber-colored eyes, which can help to identify them in a photo.

4. Nose shape: The shape and size of a tiger's nose can be used to differentiate one individual from another.

5. Body size and shape: Tigers can vary in size and shape, so noting these characteristics can help to distinguish one tiger from another.

6. Behavior: A tiger's behavior in a photo, such as posture or movement, can also provide clues to its identity.

By looking at a combination of these features, it may be possible to distinguish one tiger from another in a photo.

**Comment by sachit-menon** [comment]
Sounds good, hope you enjoy using it.
